version: "3"
services:
  hblink:
    image: hblink
    restart: always
    ports:
      - 62031:62031/udp
    volumes:
      - /srv/dmr/hblink.cfg:/opt/HBlink/hblink.cfg
      - /srv/dmr/hb_routing_rules.py:/opt/HBlink/hb_routing_rules.py
      - /srv/dmr/hb_confbridge_rules.py:/opt/HBlink/hb_confbridge_rules.py
