version: "3"
services:
  hblink:
    image: hblink
    restart: always
    ports:
      - 62031:62031/udp
    volumes:
      - [LOCALDIR]/hblink.cfg:/opt/HBlink/hblink.cfg 
      - [LOCALDIR]/hb_routing_rules.py:/opt/HBlink/hb_routing_rules.py
      - [LOCALDIR]/hb_confbridge_rules.py:/opt/HBlink/hb_confbridge_rules.py 
